# From: https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python?langId=py
name: Examples
on:
  push:
    paths-ignore:
      - 'tests/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Checkout l2metrics
        uses: actions/checkout@v2
        with:
          path: l2metrics
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest wheel
          pip install ./l2metrics
      - name: Run examples
        working-directory: ./l2metrics
        run: |
          python -m l2metrics -l ./examples/ste_logs/ste_task1_1_run1/ -s w
          python -m l2metrics -l ./examples/ste_logs/ste_task2_1_run1/ -s w
          python -m l2metrics -l ./examples/ste_logs/ste_task3_1_run1/ -s w
          python -m l2metrics -l ./examples/ste_logs/ste_task3_1_run2/ -s a
          python -m l2metrics -l ./examples/ll_logs/multi_task -p performance
          python -m l2metrics -R -l ./examples -p performance
